# Generated by Django 2.0.4 on 2018-07-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('article', models.CharField(max_length=256)),
                ('publish_time', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('url_http', models.CharField(max_length=256)),
                ('img_tp', models.CharField(max_length=256)),
                ('img_url', models.CharField(max_length=256)),
                ('comments_num', models.IntegerField(default=0)),
                ('resouces', models.CharField(max_length=256)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
