# Generated by Django 2.0.4 on 2018-07-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpSpider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnews',
            name='article',
            field=models.CharField(max_length=20000),
        ),
    ]
