# Generated by Django 2.0.4 on 2018-08-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stuno',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
