# Generated by Django 2.0.4 on 2018-08-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180809_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stuno',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
