# Generated by Django 2.0.4 on 2018-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180809_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stuno',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
