# Generated by Django 2.0.4 on 2018-08-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180809_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=128, unique=True)),
                ('departmentcode', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('createtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='departmentcode',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
