# Generated by Django 2.0.4 on 2018-05-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=128, unique=True)),
                ('blog_content', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='blog_classfies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=128, unique=True)),
                ('class_content', models.CharField(max_length=256)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='classfy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_classfies'),
        ),
    ]
