# Generated by Django 2.0.4 on 2018-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_classfies',
            name='blog_tag',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blog_classfies',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
