# Generated by Django 2.0.4 on 2018-06-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180529_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='classfy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_classfies'),
        ),
    ]
