# Generated by Django 2.0.4 on 2018-06-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180612_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='classfy',
            field=models.IntegerField(max_length=4),
        ),
    ]
