# Generated by Django 2.0.4 on 2018-06-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180630_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='access_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='editor_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='blog_classfies',
            table='blog_blog_classfies',
        ),
    ]
