# Generated by Django 2.0.4 on 2018-07-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256, null=True)),
                ('day_time', models.CharField(max_length=256, null=True)),
                ('first_time', models.DateTimeField()),
                ('last_time', models.DateTimeField()),
                ('delete', models.IntegerField(default=0)),
                ('times', models.IntegerField(default=0)),
                ('rates', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
