# Generated by Django 2.0.4 on 2018-07-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='punch_host',
            field=models.CharField(default='', max_length=256),
        ),
    ]
