# Generated by Django 2.0.4 on 2018-08-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_punch_punch_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1', models.CharField(max_length=256, null=True)),
                ('column_2', models.CharField(max_length=256, null=True)),
                ('column_3', models.CharField(max_length=256, null=True)),
                ('column_4', models.CharField(max_length=256, null=True)),
                ('column_5', models.CharField(max_length=256, null=True)),
                ('column_6', models.CharField(max_length=256, null=True)),
                ('column_7', models.CharField(max_length=256, null=True)),
                ('column_8', models.CharField(max_length=256, null=True)),
                ('column_9', models.CharField(max_length=256, null=True)),
                ('column_10', models.CharField(max_length=256, null=True)),
                ('column_11', models.CharField(max_length=256, null=True)),
                ('column_12', models.CharField(max_length=256, null=True)),
                ('column_13', models.CharField(max_length=256, null=True)),
                ('column_14', models.CharField(max_length=256, null=True)),
                ('column_15', models.CharField(max_length=256, null=True)),
                ('column_16', models.CharField(max_length=256, null=True)),
                ('column_17', models.CharField(max_length=256, null=True)),
                ('column_18', models.CharField(max_length=256, null=True)),
                ('column_19', models.CharField(max_length=256, null=True)),
                ('column_20', models.CharField(max_length=256, null=True)),
                ('field_name', models.CharField(max_length=1024, null=True)),
                ('excel_id', models.CharField(max_length=256, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('delete', models.IntegerField(default=0)),
                ('check_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Excel_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('excel_name', models.CharField(max_length=256, null=True)),
                ('is_push_check', models.IntegerField(default=0)),
                ('field_rule', models.CharField(max_length=256, null=True)),
                ('is_closed', models.IntegerField(default=0)),
                ('last_time', models.DateTimeField()),
                ('delete', models.IntegerField(default=0)),
            ],
        ),
    ]
