# Generated by Django 2.0.4 on 2018-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_excel_model_excel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_type',
            name='notice_content',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
