# Generated by Django 2.0.4 on 2018-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0004_excel_type_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_type',
            name='field_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
