# Generated by Django 2.0.4 on 2018-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0005_excel_type_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_type',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
