# Generated by Django 2.0.4 on 2018-08-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0006_auto_20180810_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_type',
            name='is_closed',
            field=models.IntegerField(default=2),
        ),
    ]
